app = "hpd-platewatch"
primary_region = "nrt"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[mounts]
  source = "data"
  destination = "/data"

[env]
  PLATE_PATTERN = "*35"
  LASTJSON_PATH = "/data/last.json"
